services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    environment:
      - MYSQL_DB_PASSWORD=supersecret
      - MYSQL_DB_USER=root
      - MYSQL_DB_HOST=workshop-db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.3
    container_name: workshop-db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=workshop
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] 
      interval: 5s         # Check every 5 seconds
      timeout: 3s          # Timeout after 3 seconds
      retries: 5           # Retry up to 5 times

volumes:
  db:
